import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Imaginify",
  description: "AI-powered image generator.",
  keywords: [
    "imagify",
    "imagifyAI",
    "imagify-generator",
    "image-generator",
    "artificial intelligence",
    "AI",
    "machine learning",
    "deep learning",
    "neural networks",
    "computer vision",
    "GANs",
    "Generative Adversarial Networks",
    "image processing",
    "image recognition",
    "image synthesis",
    "style transfer",
    "GANimation",
    "Pix2Pix",
    "CycleGAN",
    "styleGAN",
    "styleGAN2",
    "BigGAN",
    "VQGAN",
    "OpenAI",
    "TensorFlow",
    "PyTorch",
    "Keras",
    "Scikit-learn",
    "NumPy",
    "PIL",
    "OpenCV",
    "matplotlib",
    "Jupyter Notebook",
    "GAN hacks",
    "GAN hacks repository",
    "GANs in practice",
    "GANs applications",
    "GANs tutorials",
    "GANs research",
    "image datasets",
    "training data",
    "augmented data",
    "data preprocessing",
    "data augmentation",
    "image augmentation",
    "image manipulation",
    "image editing",
    "image enhancement",
    "creative AI",
    "generative art",
    "art generation",
    "creative coding",
    "visual content creation",
    "graphics programming",
    "GPU acceleration",
    "CUDA",
    "OpenCL",
    "performance optimization",
    "parallel computing",
    "distributed computing",
    "cloud computing",
    "AWS",
    "Google Cloud",
    "Azure",
    "serverless",
    "RESTful API",
    "microservices",
    "containerization",
    "Docker",
    "Kubernetes",
    "CI/CD",
    "continuous integration",
    "continuous deployment",
    "version control",
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "agile methodology",
    "scrum",
    "kanban",
    "project management",
    "issue tracking",
    "bug tracking",
    "documentation",
    "API documentation",
    "tutorials",
    "online community",
    "forum",
    "Q&A platform",
    "support",
    "user feedback",
    "user testing",
    "user experience",
    "UI design",
    "UX design",
    "front-end development",
    "HTML",
    "CSS",
    "JavaScript",
    "React",
    "Vue.js",
    "Angular",
    "WebGL",
    "Canvas API",
    "SVG",
    "responsive design",
    "mobile-first design",
    "progressive web app",
    "web accessibility",
    "performance optimization",
    "SEO",
    "search engine optimization",
    "analytics",
    "A/B testing",
    "user metrics",
    "user engagement",
    "monetization",
    "advertising",
    "sponsorship",
    "subscription model",
    "freemium model",
    "digital rights management",
    "copyright protection",
    "privacy policy",
    "terms of service",
    "GDPR compliance",
    "data security",
    "encryption",
    "authentication",
    "authorization",
    "OAuth",
    "JWT",
    "multi-factor authentication",
    "backup and recovery",
    "disaster recovery",
    "incident response",
    "ethical considerations",
    "bias mitigation",
    "fairness",
    "transparency",
    "accountability",
    "regulatory compliance",
    "intellectual property rights",
    "patents",
    "trademarks",
    "copyrights",
  ] as Array<string>,
  authors: {
    name: "Sanidhya Kumar Verma",
    url: "https://github.com/sanidhyy",
  },
} as const;

export const links = {
  sourceCode: "https://github.com/sanidhyy/imaginify",
} as const;
